export const WORDSEARCH_GENERATE = 'WORDSEARCH_GENERATE'

export const GAME_ADD_CLICK = 'GAME_ADD_CLICK'
export const GAME_CLEAR_CLICK = 'GAME_CLEAR_CLICK'
export const GAME_SET_GUESS = 'GAME_SET_GUESS'
export const GAME_FOUND_WORD = 'GAME_FOUND_WORD'
export const GAME_RESET = 'GAME_RESET'

export const MESSAGE_SET = 'MESSAGE_SET'
export const MESSAGE_CLEAR = 'MESSAGE_CLEAR'
