export const WORDSEARCH_GENERATE = 'WORDSEARCH_GENERATE'
export const WORDSEARCH_SET_GUESS = 'WORDSEARCH_SET_GUESS'
export const WORDSEARCH_INCREASE_GUESSED = 'WORDSEARCH_INCREASE_GUESSED'

export const GAME_RESET = 'GAME_RESEY'

export const MESSAGE_SET = 'MESSAGE_SET'
export const MESSAGE_CLEAR = 'MESSAGE_CLEAR'
